next.config.mjs
src/pages/_app.tsx
src/styles/_mixins.scss
src/styles/base/_normalize.scss
src/styles/base/_reset.scss
src/styles/base/index.scss

- reset scss 추가 
- next.config 에 scss 변수, 함수 적용하게 변경
-

[ chore ] reset scss 추가

---

src/lib/apis/axios.ts

- [feat] 비로그인 사용자가 로그인 필요한 페이지  접근할때 로그인 화면 으로 이동
-

[feat] 비로그인 사용자가 로그인 필요한 페이지  접근할때 로그인 화면 으로 이동

---

public/images/icon-left-arrow.svg
src/components/commons/NavTitle/NavTitle.module.scss
src/components/commons/NavTitle/index.tsx
src/lib/apis/axios.ts
src/pages/addbin/index.tsx

[Feat] nav title

---

src/components/domains/mypage/Admin/AdminPage.tsx
src/components/domains/mypage/Admin/AdminPageItem/index.tsx
src/lib/apis/admin.ts
src/pages/mypage/fix.tsx
src/pages/mypage/report.tsx

- 어드민 페이지 요청받은 쓰레기통과 수정요청 쓰레기통 페이지 api엔드포인트 수정
- 나중에 남은 신고받은 쓰레기통 페이지도 나오게 되면 수정 필요

[Fix] 어드민 페이지 요청받은 쓰레기통과 수정요청 쓰레기통 페이지 api엔드포인트 수정

---

src/components/commons/Card/index.tsx
src/components/domains/mypage/Admin/AdminPageItem/index.tsx
src/lib/apis/axios.ts
src/pages/mypage/index.tsx

- 비로그인 상태에서 마이페이지 들어가지도록 수정
- 비로그인 상태에서 마이페이지 들어가지도록 수정

[Fix] 비로그인 상태에서 마이페이지 들어가지도록 수정

---

src/components/domains/mypage/Admin/AdminPageItem/index.tsx
src/components/domains/mypage/MyPageSetting/index.tsx

[Fix] 로그인 상태 관리 수정

---

src/pages/mypage/index.tsx

fix : 로그인 상태 관리 수정

---

public/images/close.svg
src/components/domains/mypage/MyPageFindBin/MyPageToggle.module.scss
src/components/domains/mypage/MyPageFindBin/index.tsx
src/components/domains/search/SearchInput/SearchInput.module.scss
src/components/domains/search/SearchInput/index.tsx
src/components/domains/search/SearchItem/SearchItem.module.scss
src/components/domains/search/SearchItem/index.tsx
src/components/domains/search/SearchItems/SearchItem.module.scss
src/components/domains/search/SearchItems/index.tsx
src/components/domains/search/SearchToggle/SearchToggle.module.scss
src/components/domains/search/SearchToggle/index.tsx
src/lib/atoms/atom.ts
src/pages/search/index.tsx

- 검색창 기본 ui와 최근 검색 기능 제작
- 나중에 api 나오면 재작업 필요

[Feat] 검색창 기본 ui와 최근 검색 기능 제작

---

src/components/domains/mypage/MyPageFindBin/index.tsx
src/components/domains/mypage/MyPageSetting/index.tsx
src/pages/mypage/index.tsx

- 마이페이지 에러 수정
- 마이페이지 내 정보 가져오기 ssr 수정
- 로그아웃시 가려하 하는 정보 수정

[Fix] 마이페이지 에러 수정

---

src/components/commons/Gnb/Gnb.module.scss
src/components/domains/addBin/addBinForm/index.tsx
src/pages/index.tsx
src/pages/testkakao/index.tsx

[fix] Gnb z-index 5

---

package-lock.json
package.json
src/components/domains/addBin/addBinForm/ImgInput.tsx
src/components/domains/addBin/addBinForm/index.tsx
src/pages/_app.tsx
src/pages/addbin/index.tsx

[Fix] gnb 로그인창에서 숨기기

---

src/pages/_app.tsx
src/pages/_document.tsx

[Feat] 구글 애널리틱스 연결

---

src/components/commons/DropBottom/DropReason/index.tsx
src/components/commons/DropBottom/index.tsx
src/components/domains/mypage/Admin/AdminDetail.tsx
src/lib/apis/ask.ts
src/lib/apis/postRejectAddbin.ts
src/lib/constants/modalContents.ts
src/pages/mypage/ask/[id].tsx
src/pages/mypage/fix/[id].tsx

- [feat ] ask 거절, 승인 확인 후 모달 띄우기
-

[feat ] ask 거절, 승인 확인 후 모달 띄우기

---

src/components/commons/DropBottom/DropReason/index.tsx
src/components/commons/DropBottom/index.tsx
src/components/commons/NavTitle/NavTitle.module.scss
src/components/domains/mypage/Admin/AdminDetail.tsx
src/lib/apis/ask.ts
src/lib/apis/postRejectAddbin.ts
src/lib/constants/modalContents.ts
src/pages/mypage/ask/[id].tsx
src/pages/mypage/fix/[id].tsx

[Fix] addbin 페이지 ui

---

src/components/commons/DropBottom/DropProfileEdit/index.tsx

[Fix] 마이페이지 정보 수정 조건 수정

---

src/components/commons/Modal/Share/index.tsx

[Fix] url 복사하기 수정

---

src/components/domains/home/KakaoMap/index.tsx

[fix] api load error

---

src/components/domains/home/KakaoMap/index.tsx

[fix ] bindata load error

---

src/components/commons/Modal/Share/index.tsx
src/components/domains/home/KakaoMap/index.tsx

[fix] 환경변수 재설정

---

src/components/commons/Modal/Share/index.tsx
src/components/domains/home/KakaoMap/index.tsx

Fix 환경변수 재수정

---

src/components/commons/Gnb/Gnb.module.scss
src/components/commons/Gnb/index.tsx
src/components/domains/mypage/Admin/AdminPageItem/index.tsx
src/components/domains/mypage/MyPageNoti/MyPageNoti.module.scss
src/components/domains/mypage/MyPageNoti/NotiItem.tsx
src/components/domains/mypage/MyPageNoti/index.tsx
src/components/domains/mypage/MyPageProfile/index.tsx
src/lib/apis/noti.ts
src/lib/atoms/userAtom.ts
src/lib/constants/binType.ts
src/lib/constants/notiText.ts
src/pages/_app.tsx

- 무한스크롤 가능하게 구현
- api와 연결해 알림삭제, 알림이 있는지 확인 등 제작 
-

[Feat] 알림페이지 api와 연결해서 구현

---

src/components/domains/addBin/addBinForm/AddBinForm.module.scss
src/components/domains/addBin/addBinForm/index.tsx
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/components/domains/home/KakaoMap/index.tsx
src/components/domains/mypage/MyPageFindBin/MyPageToggle.module.scss

- 아이폰 하단 주소창에 밀려 gnb와 겹치는 버튼들 수정
- 배포 후 다시 모바일에서 확인 필요

[Fix] 에러 수정

---

src/pages/_app.tsx
src/styles/_mixins.scss
src/styles/base/_normalize.scss

[Fix] 반응형 대비해 app 스타일 따로 작성

---

src/components/domains/home/Tutorial/tutorial.module.scss
src/components/domains/search/SearchDetail/SearchDetail.module.scss
src/components/domains/search/SearchDetail/index.tsx
src/components/domains/search/SearchInput/index.tsx
src/components/domains/search/SearchItems/index.tsx
src/components/domains/search/SearchToggle/index.tsx
src/lib/apis/bookmarks.ts
src/lib/atoms/atom.ts
src/lib/atoms/userAtom.ts
src/pages/_app.tsx
src/pages/search/index.tsx

- 검색 즐겨찾기까지 구현
- 온보딩과 튜토리얼 꼬여있던것 수정
- 사용자가 편하게 이전 검색 기록 누르면 바로 검색 가능하게 수정
-

[Feat] : 검색 즐겨찾기까지 구현

---

src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/commons/DropBottom/DropBinInfo/useBinActions.ts
src/components/commons/NavTitle/index.tsx
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/components/domains/home/KakaoMap/index.tsx
src/lib/apis/likes.ts

- [feat] binDetail actions  api 연결
- map height  조정 중
- 머지 후에 브레이크 포인트 별로 텍스트 조절할게유,,

[feat] binDetail actions  api 연결

---

src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/commons/Toast/Toast.module.scss
src/components/domains/addBin/addBinForm/index.tsx
src/components/domains/home/AroundBinSearchBtns/AroundBinSearchBtns.module.scss
src/components/domains/home/KakaoMap/index.tsx
src/components/domains/home/RecommendCard/RecommendCard.module.scss
src/lib/apis/admin.ts
src/lib/map/markers.ts
src/pages/mypage/ask/[id].tsx

- [fix ] 관리자 수정하기 요청시 폼에 데이터 가져오기
-

[fix ] 관리자 수정하기 요청시 폼에 데이터 가져오기

---

src/components/domains/mypage/MyPageProfile/index.tsx

fix : 이미지 에러 수정

---

src/components/commons/Card/Card.module.scss
src/components/commons/Card/index.tsx
src/components/commons/DropBottom/dropBottom.module.scss
src/components/commons/Modal/Share/BookmarkNoti.tsx
src/components/commons/Modal/Share/Share.module.scss
src/components/domains/mypage/Admin/AdminDetail.module.scss
src/components/domains/mypage/MyPageNoti/NotiItem.tsx
src/components/domains/search/SearchDetail/index.tsx
src/components/domains/search/SearchInput/index.tsx
src/components/domains/search/SearchItems/SearchItem.module.scss
src/components/domains/search/SearchItems/index.tsx
src/components/domains/search/SearchToggle/index.tsx
src/lib/apis/bookmarks.ts
src/lib/constants/date.ts
src/lib/constants/notiText.ts
src/pages/search/index.tsx

- 검색 엔터 적용
- 로그인 안한상태 하단 모달
- 알림 수정
-

[Feat] 검색 엔터 적용, 로그인 안한상태 하단 모달, 알림 수정

---

src/components/commons/DropBottom/dropBottom.module.scss
src/components/commons/Gnb/index.tsx

[Fix] : 위치값 수정

---

src/styles/base/_normalize.scss

[Fix] height값 조절

---

src/pages/_app.tsx
src/styles/base/_normalize.scss

fix : height값 조절

---

src/components/domains/home/KakaoMap/index.tsx

[Fix] search 관련 업데이트 이후 홈 맵에러 해결

---

src/components/domains/home/BinTypeBtnList/index.tsx
src/components/domains/home/KakaoMap/index.tsx
src/lib/mapUtills/initializeMap.ts
src/lib/mapUtills/useKakaoMap.ts

[fix] map 안나타는 오류 해결

---

src/components/commons/DropBottom/DropBinInfo/DropBinInfo.module.scss
src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/commons/DropBottom/DropInfo/DropInfo.module.scss
src/components/domains/addBin/addBinForm/AddBinForm.module.scss
src/components/domains/addBin/addBinForm/Input.tsx
src/components/domains/addBin/addBinForm/index.tsx
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/components/domains/home/KakaoMap/SearchBtn.tsx
src/components/domains/home/KakaoMap/index.tsx
src/lib/apis/postAddbin.ts
src/lib/atoms/editAtom.ts
src/lib/mapUtills/getAddressFromCoords.ts
src/lib/mapUtills/useKakaoMap.ts
src/pages/mypage/ask/[id].tsx
src/pages/mypage/detail/[id].tsx
src/pages/mypage/edit/[id].tsx
src/pages/mypage/fix/[id].tsx
src/types/addFormTypes.ts

[Fix] 쓰레기통 수정하기 변경사항 수정

---

src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/commons/DropBottom/DropCancel/DropCancel.module.scss
src/components/commons/DropBottom/DropCancel/index.tsx
src/components/commons/DropBottom/DropProfileEdit/DropProfileEdit.module.scss
src/components/commons/DropBottom/DropProfileEdit/Img.tsx
src/components/commons/DropBottom/DropProfileEdit/index.tsx
src/components/commons/DropBottom/DropReason/index.tsx
src/components/commons/DropBottom/dropBottom.module.scss
src/components/domains/addBin/addBinForm/index.tsx
src/components/domains/home/KakaoMap/index.tsx
src/components/domains/home/RecommendCard/index.tsx
src/components/domains/mypage/Admin/AdminDetail.module.scss
src/components/domains/mypage/Admin/AdminDetail.tsx
src/components/domains/mypage/Admin/AdminPageBar/index.tsx
src/components/domains/mypage/MyPageNoti/index.tsx
src/components/domains/search/SearchDetail/SearchDetail.module.scss
src/components/domains/search/SearchInput/SearchInput.module.scss
src/components/domains/search/SearchItems/index.tsx
src/components/domains/search/SearchToggle/index.tsx
src/lib/apis/members.ts
src/lib/hooks/useDrag.ts
src/pages/location/index.tsx
src/pages/mypage/ask/[id].tsx

- 다크모드 색 수정
- 콘솔 제거
- 검색 즐겨찾기 누르면 이동하도록 수정
-

[Fix] 에러난 부분들 수정

---

global.d.ts
src/components/commons/Gnb/index.tsx
src/pages/_app.tsx

[Feat] : gtag추가

---

src/components/commons/Gnb/index.tsx

[Fix]: gtag추가 에러 수정

---

src/components/domains/search/SearchInput/index.tsx
src/components/domains/search/SearchItem/index.tsx
src/components/domains/search/SearchItems/index.tsx
src/components/domains/search/SearchToggle/index.tsx
src/pages/search/index.tsx

[Fix] : search 비로그인 최근검색 수정

---

src/components/commons/DropBottom/DropBinInfo/DropBinInfo.module.scss
src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/domains/home/CommentList/CommentForm/CommentForm.module.scss
src/components/domains/home/CommentList/CommentList.module.scss
src/lib/mapUtills/loadKakaoMapScript.ts

- [Fix] 맵 로드 오류, 댓글 폼 클릭시 드롭다운으로 변경되는 오류 , 댓글 폼 버튼 css 오류  수정
-

[Fix] 맵 로드 오류, 댓글 폼 오류  수정

---

src/components/commons/DropBottom/DropBinInfo/DropBinInfo.module.scss
src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/domains/home/CommentList/CommentForm/CommentForm.module.scss
src/components/domains/home/CommentList/CommentList.module.scss
src/components/domains/home/CommentList/index.tsx
src/lib/hooks/useDrag.ts
src/lib/mapUtills/loadKakaoMapScript.ts

[Fix] 스크롤했을 때 드레그 막기 

---

src/components/domains/search/SearchDetail/SearchDetail.module.scss

[Fix] 디자인 깨지는것 수정

---

src/components/commons/Gnb/index.tsx

[Fix] 페이지 이동할때 알림 가져오게 수정

---

src/components/commons/DropBottom/DropBinInfo/index.tsx
src/lib/atoms/userAtom.ts
src/pages/index.tsx

[ fix ] 모바일 홈 스크롤 새로고침 막기

---

src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/components/domains/home/RecommendCard/index.tsx
src/lib/atoms/userAtom.ts
src/lib/hooks/useDrag.ts
src/pages/index.tsx

[fix ] useDrag 훅 수정

---

src/components/domains/home/BinTypeBtnList/BinTypeBtnList.module.scss

- [ fix ] 홈 버튼리스트 크롬에서 스크롤 숨기기
-

[ fix ] 홈 버튼리스트 크롬에서 스크롤 숨기기

---

src/lib/hooks/useDrag.ts

[Fix] 댓글 드래그 막힌거 해결

---

src/components/commons/Gnb/index.tsx
src/components/domains/home/AroundBinSearchBtns/index.tsx
src/components/domains/home/KakaoMap/index.tsx
src/lib/hooks/useToggle.ts

[Fix] 위치 따라오기 아이콘 5초마다 따라오게 설정

---

src/components/commons/Toast/Toast.module.scss
src/components/domains/home/HomeLayOut/HomeLayOut.module.scss
src/components/domains/home/HomeLayOut/index.tsx
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/components/domains/home/KakaoMap/index.tsx
src/pages/index.tsx
src/pages/signin/index.tsx

[ fix ] 맵 덜컹거리는 거 수정

---

.github/workflows/deploy.yml
build.sh

[fix] 배포 오류 해결

---

src/components/domains/search/SearchInput/index.tsx
src/components/domains/search/SearchItems/index.tsx
src/pages/search/index.tsx

- 검색 후 최근검색 돌아오면 최신화 안되는 에러 수정
-

[Fix] 검색 후 최근검색 돌아오면 최신화 안되는 에러 수정

---

src/components/domains/home/KakaoMap/index.tsx
src/components/domains/home/Tutorial/Slide4.tsx
src/components/domains/home/Tutorial/tutorial.module.scss

fix : 튜토리얼 수정

---

public/manifest.json
public/sw.js

fix : sw 수정

---

src/components/commons/DropBottom/DropBinInfo/DropBinInfo.module.scss
src/components/domains/home/AroundBinSearchBtns/AroundBinSearchBtns.module.scss
src/components/domains/home/RecommendCard/RecommendCard.module.scss
src/components/domains/home/RecommendCard/index.tsx

[fix] 추천카드 css

---

src/components/commons/DropBottom/DropBinInfo/DropBinInfo.module.scss
src/components/domains/home/AroundBinSearchBtns/AroundBinSearchBtns.module.scss
src/components/domains/home/BinTypeBtnList/BinTypeBtnList.module.scss
src/components/domains/home/HomeLayOut/HomeLayOut.module.scss
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/components/domains/home/RecommendCard/RecommendCard.module.scss
src/components/domains/home/RecommendCard/index.tsx

[Fix] mapcss 모바일 스크롤 막기

---

public/manifest.json
public/sw.js
src/components/commons/DropBottom/DropBinInfo/DropBinInfo.module.scss
src/components/commons/Modal/Modal.module.scss
src/components/domains/home/AroundBinSearchBtns/AroundBinSearchBtns.module.scss
src/components/domains/home/BinTypeBtnList/BinTypeBtnList.module.scss
src/components/domains/home/HomeLayOut/HomeLayOut.module.scss
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/components/domains/home/RecommendCard/RecommendCard.module.scss

[fix] 자잘한 오류 수정

---

src/components/Skeleton/AdminCardSkel/AdminCardSkel.module.scss
src/components/Skeleton/AdminCardSkel/index.tsx
src/components/commons/Splash/index.tsx
src/components/domains/home/HomeLayOut/HomeLayOut.module.scss
src/components/domains/home/KakaoMap/index.tsx
src/components/domains/home/RecommendCard/RecommendCard.module.scss
src/components/domains/mypage/Admin/AdminPageItem/index.tsx

- 맵 눌렀을 때 추천카드 사라지게 + 모바일 map 테스트
-

맵 눌렀을 때 추천카드 사라지게 + 모바일 map 테스트

---

src/components/Skeleton/AdminCardSkel/AdminCardSkel.module.scss
src/components/Skeleton/AdminCardSkel/index.tsx
src/components/commons/Splash/index.tsx
src/components/commons/Toast/Toast.module.scss
src/components/domains/home/HomeLayOut/HomeLayOut.module.scss
src/components/domains/home/KakaoMap/index.tsx
src/components/domains/home/RecommendCard/RecommendCard.module.scss
src/components/domains/mypage/Admin/AdminPageItem/index.tsx

- [Fix] 모바일 맵 추천 카드 숨는 css 수정
-

[Fix] 모바일 맵 추천 카드 숨는 css 수정 & 어드민 페이지 카드 스켈레톤 추가

---

src/components/commons/CardList/index.tsx
src/components/commons/DropBottom/DropBinInfo/index.tsx
src/components/commons/DropBottom/DropBinInfo/useBinActions.ts
src/components/domains/home/CommentList/index.tsx

- [fix] api 변경에 따른 bintype 저장
-

[fix] api 변경에 따른 bintype 저장

---

src/components/Skeleton/AdminCardSkel/AdminCardSkel.module.scss
src/components/Skeleton/AdminCardSkel/index.tsx
src/components/commons/Splash/index.tsx
src/components/domains/home/KakaoMap/index.tsx
src/components/domains/home/RecommendCard/RecommendCard.module.scss
src/components/domains/mypage/Admin/AdminPageItem/index.tsx
src/components/domains/search/SearchDetail/SearchDetail.module.scss
src/components/domains/search/SearchInput/SearchInput.module.scss

[Fix] 검색창 깨지는거 수정

---

src/components/domains/home/AroundBinSearchBtns/AroundBinSearchBtns.module.scss
src/components/domains/home/BinTypeBtnList/BinTypeBtnList.module.scss
src/components/domains/home/KakaoMap/KakaoMap.module.scss

[ fix ] 정렬 맞추기

---

src/components/domains/home/AroundBinSearchBtns/AroundBinSearchBtns.module.scss
src/components/domains/home/BinTypeBtnList/BinTypeBtnList.module.scss
src/components/domains/home/KakaoMap/KakaoMap.module.scss

[fix] 버튼 정렬 맞추기

---

src/lib/mapUtills/getAddressFromCoords.ts
src/lib/mapUtills/initMap.ts

- [fix ] application-- error 수정 test
-

[fix ] application-- error 수정 test

---

src/components/domains/home/AroundBinSearchBtns/AroundBinSearchBtns.module.scss
src/components/domains/home/BinTypeBtnList/BinTypeBtnList.module.scss
src/components/domains/home/KakaoMap/KakaoMap.module.scss
src/lib/mapUtills/getAddressFromCoords.ts
src/lib/mapUtills/initMap.ts

- [fix] application-- error 수정 test
-

[fix] application-- error 수정 test

---

src/components/domains/home/KakaoMap/index.tsx
src/lib/mapUtills/getAddressFromCoords.ts
src/lib/mapUtills/initMap.ts

[Fix] map 중앙 좌표 저장 속도 개선

---

src/components/domains/home/KakaoMap/index.tsx

- [fix] 중앙좌표값 찾는 시간 테스트 0.1초
-

[fix] 중앙좌표값 찾는 시간 수정 테스트

---

src/components/domains/addBin/addBinForm/Input.tsx
src/components/domains/home/KakaoMap/index.tsx
src/lib/mapUtills/getAddressFromCoords.ts
src/pages/index.tsx
src/pages/search/[id].tsx

[fix] home load error

---

src/components/domains/home/KakaoMap/index.tsx
src/pages/index.tsx

[fix] 지도 해상도 오류 테스트 200

---

src/components/domains/home/KakaoMap/index.tsx
src/pages/index.tsx

[fix] 지도 해상도 오류 테스트 300

---

src/components/domains/home/KakaoMap/index.tsx
src/lib/mapUtills/initMap.ts

- [fix] 맵 두번 로드되는 오류 해결 + 200
-

[fix] 맵 두번 로드되는 오류 해결 + 200

---

src/components/commons/Gnb/index.tsx
src/lib/apis/axios.ts
src/lib/mapUtills/useKakaoMap.ts

- 서버 연결 중단 이슈로 일어난 오류 해결
- 목데이터 작업 후 업데이트 예정

fix : 네트워크 연결  관련오류수정

---

src/components/domains/home/KakaoMap/index.tsx
src/lib/apis/axios.ts
src/lib/mapUtills/useBinData.ts
src/lib/mock/MOCK_DATA (1).json
src/lib/mock/getRandomLocation.ts

… 좌표 뿌려주는 함수 생성
-  쓰레기통 목데이터 초안 생성 
-  주변 랜덤한 좌표 뿌려주는 함수 생성
-

fix : network error 고치는 중... 자리이동 이슈로 인한 커밋
